---
kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src/git.ana/xjtuana

platform:
  arch: amd64
  os: linux

trigger:
  branch:
    - master

steps:
  - name: build
    image: docker.io/library/golang:latest
    environment:
      CGO_ENABLED: 0
      GOARCH: amd64
      GOOS: linux
      GOINSECURE: git.ana
      GOPRIVATE: git.ana
    commands:
      - go version
      - go mod download
      - go test -v ./...
      - go build -ldflags="-w -s" -trimpath -o build/server_linux_amd64 cmd/server/main.go

  - name: publish
    image: registry.dev.xjtuana.cn/plugins/docker:latest
    privileged: true
    settings:
      auto_tag: true
      registry: registry.dev.xjtuana.cn
      repo: registry.dev.xjtuana.cn/xjtuana/api-micro-mail
