log:
  level: debug
  file: ""

plugins:
  - tag: forward_domestic
    type: forward
    args:
      upstreams:
        - addr: '119.29.29.29:53'
        - addr: '223.5.5.5:53'

  - tag: forward_non_domestic
    type: forward
    args:
      upstreams:
        - tag: google_doh
          addr: "https://dns.google/dns-query"
          dial_addr: "8.8.8.8"
          socks5: "10.58.17.201:1080"
  - tag: ana_domain
    type: "hosts"
    args:
      files:
        - "ana-hosts.txt"

  - tag: use_cache
    type: cache
    args:
      size: 8192

  - tag: main_sequence
    type: sequence
    args:
      - matches:
        - qname domain:ana
        exec: $ana_domain
      - matches:
        - "!qname domain:ana"
        exec: $forward_non_domestic
      - exec: cache 1024

  - tag: server
    type: udp_server
    args:
      entry: main_sequence
      listen: 0.0.0.0:53

  - tag: http_server
    type: http_server
    args:
      entries:
        - path: /dns-query
          exec: main_sequence
      listen: 0.0.0.0:80

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: 0.0.0.0:5353

include: []

